version: '2.2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - elevate_net
    logging:
      driver: none
  kafka:
    image: 'confluentinc/cp-kafka:7.3.0'
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - elevate_net
    logging:
      driver: none
  redis:
    image: 'redis:7.0.0'
    container_name: redis
    restart: 'always'
    command: redis-server --appendonly yes --maxmemory-policy noeviction
    ports:
      - '6380:6379'
    networks:
      - elevate_net

  scheduler:
    image: shikshalokamqa/elevate-scheduler:2.2
    ports:
      - '3000:3001'
    command: ['nodemon', 'app.js']
    environment:
      - MONGODB_URL=mongodb://mongo:27017/elevate-scheduler
      - KAFKA_URL=kafka:9092
    env_file:
      - ${env_file}
    depends_on:
      - kafka
      - redis
    networks:
      - elevate_net
networks:
  elevate_net:
    external: false
volumes:
  zookeeper-data:
  kafka-data:
